import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import vaultRouter from "./vault";
import grailRouter from "./grail";
import tradesRouter from "./trades";
import forumRouter from "./forum";
import portfolioRouter from "./portfolio";
import dashboardRouter from "./dashboard";
import activityRouter from "./activity";
import aiRouter from "./ai";
import billingRouter from "./billing";
import psaRouter from "./psa";
import ebayRouter from "./ebay";
import rebrickableRouter from "./rebrickable";
import pricechartingRouter from "./pricecharting";
import scryfallRouter from "./scryfall";
import pokemonRouter from "./pokemon";
import tcgapiRouter from "./tcgapi";
import justtcgRouter from "./justtcg";
import cardhedgerRouter from "./cardhedger";
import messagesRouter from "./messages";
import communityRouter from "./community";

const router: IRouter = Router();

router.use(healthRouter);
router.use(profileRouter);
router.use(vaultRouter);
router.use(grailRouter);
router.use(tradesRouter);
router.use(forumRouter);
router.use(portfolioRouter);
router.use(dashboardRouter);
router.use(activityRouter);
router.use(aiRouter);
router.use(billingRouter);
router.use(psaRouter);
router.use(ebayRouter);
router.use(rebrickableRouter);
router.use(pricechartingRouter);
router.use(scryfallRouter);
router.use(pokemonRouter);
router.use(tcgapiRouter);
router.use(justtcgRouter);
router.use(cardhedgerRouter);
router.use(messagesRouter);
router.use(communityRouter);

export default router;
